version: '3.9'

services:

  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    container_name: db
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    env_file: .env
    restart: always
    network_mode: "bridge"
    ports:
      - 5432:5432
    networks:
      - my-network
    environment:
      POSTGRES_DB: "easyshare"
      POSTGRES_USER: "easyshare"
      POSTGRES_PASSWORD: "ssdfdsf3erEWFD"

  flask:
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    container_name: flask
    restart: always
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
    env_file: .env
    depends_on:
      - db
    network_mode: "bridge"
    links:
      - db
    networks:
      - my-network

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        - project_env=dev
    container_name: nginx
    restart: always
    network_mode: "bridge"
    env_file: .env
    depends_on:
      - flask
    links:
      - flask
    networks:
      - my-network
    ports:
      - 80:80
      - 443:443

volumes:
  postgres:

networks:
  my-network: