name: CI/CD Workflow
on: [push, workflow_dispatch]
jobs:
  docker-compose-build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.DIRECTORY }}
            git pull origin master
            docker-compose -f docker-compose.prod.yml up --build -d